// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IERC5564Announcer
 * @notice Standard interface for the ERC-5564 stealth address announcement contract.
 * Emits an on-chain event allowing recipients to scan and detect stealth payments using their viewing key.
 */
interface IERC5564Announcer {
    /**
     * @notice Emitted when a stealth transfer or interaction occurs.
     * @param schemeId The stealth address scheme identifier (1 = secp256k1 with view tag)
     * @param stealthAddress The derived one-time destination address
     * @param caller The address that triggered the announcement (e.g., AlloyHarvestRouter)
     * @param ephemeralPubKey The ephemeral public key (R) generated by the sender (33 bytes compressed)
     * @param metadata Arbitrary payload including the 1-byte view tag
     */
    event Announcement(
        uint256 indexed schemeId,
        address indexed stealthAddress,
        address indexed caller,
        bytes ephemeralPubKey,
        bytes metadata
    );

    /**
     * @notice Broadcasts an announcement for a stealth transaction.
     * @param schemeId The stealth address scheme identifier
     * @param stealthAddress The one-time address receiving funds
     * @param ephemeralPubKey The sender's ephemeral public key
     * @param metadata Supplementary data (e.g. view tag, token address, amount)
     */
    function announce(
        uint256 schemeId,
        address stealthAddress,
        bytes memory ephemeralPubKey,
        bytes memory metadata
    ) external;
}
